name: Nightly Build (Essentials)
run-name: dockware/shopware-essentials:dev-main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:

  on-push:
    name: Release Image
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v4

      - name: Release Essentials dev-main
        uses: ./.github/actions/circleci
        with:
          # -------------------------------------------
          IMAGE: shopware-essentials
          VERSION: dev-main
          IS_LATEST: false
          # -------------------------------------------
          CIRCLECI_KEY: ${{ secrets.CIRCLE_CI_TOKEN }}